command:
  - uvicorn
  - app.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: HOST
    value: "https://sap-bdc-5347428297913551.11.azure.databricksapps.com"
  - name: DATA_DIR
    value: "/tmp/sap_bdc_data"
